---

language: node_js

node_js:
  - 7
  - 6
  - 5
  - 4

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: npm
  email:
    secure: MG/ZqMSDryjrzbXf9qGNP3ro6XPnPw2MO+EByCT9ucYTCFP7jXah1T/57Km4T3yU3vjWz0c0e1kGyUNJv0R0CX5zaPFKPSlbQoaY44/qrhDA7SlbPmMhqZm77oDVCnRf+0UYBrtU2MYHBIOYE+F6HIWSkNf1G2SL4rbeXeRM79tngCGxlfPkyEzlPzaguzskPZt+DPKlhHbqdtQdldB9JXq3HdQFa/SXyts+mYZpBGhR6KM8jJcelyzVDX5Yg6loNC1a/211qxNlF2TcfusC78doJEQyRElRgrDxsln4R3jQyhe6WE/93bqT962lidfgCzOrta178BEkAkVG5zHsHFxqcFuZCuYdor7JyjB5bkzWJgM753Gsd6zdyh08NPZFrFa+9gZZXMQHZnstSpW41EFYDEbCw0yl0wpB+xN+cdKhW5oZY3pnRH2pgfHQrKRb6pRbtFWL4RC5EGYa9b7WGwkeXks7LKqzBRikjRtau/RVY/rFmur2pKI2ezbUZm9G1gVCEvwMXehmOEWtTUig6Ex1/rWHN7UdH+7P+44DSV2+mDbBCLPMnowrjL1Jf/doVECvnJAcxCG0rV/rj4A9beVGfIAG0hnFt+/bdL7igjolz10dJk+Typ/uEzIDeEsX3Eo2+gQohH78MyRpppN4ORB7egzJd2W0V4d4D3QSiwU=
  api_key:
    secure: lvvdsXPi6g8neCIurAEYhG4W7f/cXZx+CE4jbl8sxyEErAxCrqckwJwAWdv8Fg+Xem6RfrQuApUu+Tohp84JlKeOY+o0JwRjtV42m98fRCyhekptf7xzYwnxaWwkpuISA/qzt3rb2q8DyVboGd2oOYFLf4Iuz1LK8t5bJHTQcxOJersMaFBapMfNDj6ohNskunfbn9sEbIpaGxFbouWUYtqa993cOLlf/ka7iEhaWVhb+qiO7Jff2U8ImJe6pxUCHWyw2dFlQ3fFF3jlgvOxYM/OPys135zi0VqjIOqHx27SHx3OvwBjFZISfx5soo93/NJT4nxChj5gCvqTXT+ByGRi0lObtqN1YsCEEnybqBpwyoq0t17nKL6916W//pUnb2zTGZVfJLDSE7HuA6FgGJqYnjWsHfD80DEB6wvHA0dhNrhDtPT99qSNmiDHg8Ts98r2fXIdKR4TOmKbyBU6A4I6VPjOVEmJiO8A8c3taUeXwQYWfAgmX0nGsPPD8/VI1md5gvFHqkyN/Wz8D/DHu83BIweHlSsZ155rKVx/Y55gV3FQEk3u9BrTGXdjXaJ6vq9UQ4UTV6ZMKwWVBzgMdOxdC62cJPLQnUcSxkHyOUNV+yAa+Ae1cgyw2Cd3oYn6DDPHMKULIEU8jXnNfpdCrlRyhZeZqniHgXCtfv6eq+w=
  on:
    tags: true
    repo: astorije/fulky
